---
title: "Long-term WQ: Sampling Effort from DroughtData"
author: "Dave Bosworth"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = 'docs',
      envir = globalenv()
    )
    })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

Look at the sampling effort for the various parameters to be included in the long-term WQ publication. This will help us decide how to structure our ANOVA models.


# Global code and functions

```{r load packages, message = FALSE, warning = FALSE}
# Load packages
library(tidyverse)
library(lubridate)
library(scales)
library(here)
```

```{r check dir}
# Check if we are in the correct working directory
i_am("Sampling_Effort_DroughtData.Rmd")
```

```{r session info}
# Run session info to display package versions
devtools::session_info()
```


# Import and Prepare Data

```{r import data, message = FALSE}
# Import raw data stored on this repo for now
fp_data <- here("data_temp/")

df_wq <- read_csv(file.path(fp_data, "raw_wq_1975_2021.csv"))
df_nutr <- read_csv(file.path(fp_data, "raw_nutr_1975_2021.csv"))
df_chla <- read_csv(file.path(fp_data, "raw_chla_1975_2021.csv"))
```


```{r prepare data}
# Define factor level for Region
region_lev <- c(
  "North",
  "SouthCentral",
  "Confluence",
  "Suisun Bay",
  "Suisun Marsh"
)

# Define factor level for Season
season_lev <- c(
  "Winter",
  "Spring",
  "Summer",
  "Fall"
)

# Create a nested data frame and prepare to run the summary plot function on
ndf_lt_wq <- 
  tibble(
    Parameter = c(
      "Temperature",
      "Salinity",
      "Secchi",
      "DissAmmonia",
      "DissNitrateNitrite",
      "DissOrthophos",
      "Chlorophyll"
    ),
    df_data = c(
      rep(list(df_wq), 3),
      rep(list(df_nutr), 3),
      list(df_chla)
    )
  ) %>% 
  mutate(
    df_data_c = map2(
      df_data, 
      Parameter,
      ~ drop_na(.x, all_of(.y)) %>% 
        mutate(
          Region = factor(Region, levels = region_lev),
          Season = factor(Season, levels = season_lev)
        )
    )
  )
```


# Create Plots

```{r plot func}
# Create function for sampling effort plots
plot_samp_effort <- function(df) {
  df %>% 
    count(YearAdj, Season, Region, name = "num_samples") %>% 
    ggplot(aes(x = YearAdj, y = Region, fill = num_samples)) +
    geom_tile() +
    facet_grid(rows = vars(Season)) +
    scale_x_continuous(breaks = breaks_pretty(20), expand = expansion()) +
    scale_fill_viridis_c(name = "Number of Samples") +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
      legend.position = "top"
    )
}
```

```{r create plots}
# Create plots for each Parameter
ndf_lt_wq_plt <- ndf_lt_wq %>% mutate(plt = map(df_data_c, .f = plot_samp_effort))
```

# Sampling Effort {.tabset .tabset-pills}

```{r print plots, echo = FALSE, results = "asis", fig.width = 8, fig.height = 7}
for (i in 1:nrow(ndf_lt_wq_plt)) {
  # Create subheadings for each Parameter
  cat("## ", ndf_lt_wq_plt$Parameter[i], "\n\n")
  # Print plot
  print(ndf_lt_wq_plt$plt[[i]])
  cat("\n\n")
}
```

